gscam_publisher:
  ros__parameters:
    gscam_config: 'v4l2src device=/dev/video0 do-timestamp=true ! queue'
    preroll: True
    use_gst_timestamps: True
    camera_name: 'my_camera'
    frame_id: 'my_camera_frame'
