################################################################################
#
#  Copyright (C) 2020 Garrett Brown
#  This file is part of the beachfronter repo - https://github.com/eigendude/beachfronter
#
#  SPDX-License-Identifier: Apache-2.0
#  See the file LICENSE.txt for more information.
#
################################################################################

#
# This workflow will install development dependencies and run tests.
#
# For more information see:
#
#   https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
#

name: Webhud client

# Controls when the action will run. Triggers the workflow on push or pull
# request events but only for the master branch
#on:
#  push:
#    branches: [master, test]
#  pull_request:
#    branches: [master, test]
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in
# parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-18.04
          - os: ubuntu-20.04

    steps:
      - name: Build environment information
        run: 'echo "Matrix OS: ${{ matrix.os }} on $HOSTNAME with $(getconf _NPROCESSORS_ONLN) cores"'

      # Checks-out the repository under $GITHUB_WORKSPACE, so the job can
      # access it
      - uses: actions/checkout@v2

      - name: apt install <depends>
        if: matrix.os != 'macOS'
        run: |
          sudo apt update || true
          dpkg -s gstreamer1.0-nice || sudo apt install -y gstreamer1.0-nice
          dpkg -s gstreamer1.0-plugins-bad || sudo apt install -y gstreamer1.0-plugins-bad
          dpkg -s gstreamer1.0-plugins-base || sudo apt install -y gstreamer1.0-plugins-base
          dpkg -s gstreamer1.0-plugins-good || sudo apt install -y gstreamer1.0-plugins-good
          dpkg -s libgstreamer-plugins-bad1.0-dev || sudo apt install -y libgstreamer-plugins-bad1.0-dev
          dpkg -s libgstreamer-plugins-base1.0-dev || sudo apt install -y libgstreamer-plugins-base1.0-dev
          dpkg -s libgstreamer-plugins-good1.0-dev || sudo apt install -y libgstreamer-plugins-good1.0-dev
          dpkg -s libgstreamer1.0-dev || sudo apt install -y libgstreamer1.0-dev
          dpkg -s libjson-glib-dev || sudo apt install -y libjson-glib-dev
          dpkg -s libsoup2.4-dev || sudo apt install -y libsoup2.4-dev

      #- name: brew install <depends>
      #  if: matrix.os == 'macOS'
      #  run: |
      #    brew update && brew install python

      # Build the client
      - name: Build client
        run: |
          make
        working-directory: webhud/client

      # Run the client
      - name: Run client
        run: |
          ./webrtc-sendrecv || ([ "$?" -eq 255 ] && echo "Exit code 255")
        working-directory: webhud/client
